development: &local
  adapter: postgresql
  database: mokatest-dev
  host: localhost
  username: postgres
  password: postgres
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: mokatest-test
  host: localhost
  username: postgres
  password: postgres
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: mokatest
  host: localhost
  username: postgres
  password: 12345678
  port: 5432
  pool: 5
  timeout: 5000
