development: &local
  adapter: postgresql
  database: mokadev
  host: localhost
  username: shail3sh
  password:
  port: 5432
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: mokatest
  host: localhost
  username: shail3sh
  password:
  port: 5432
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: mokaprod
  host: localhost
  username: shail3sh
  password:
  port: 5432
  pool: 5
  timeout: 5000
