default: &default
  adapter: postgresql
  host: localhost
  username: postgres
  password: 12345678
  port: 5432
  pool: 5
  timeout: 5000

development: 
  <<: *default
  database: mokadev

test:
  <<: *default
  database: mokatest

production:
  adapter: postgresql
  database: mokatest
  host: localhost
  username: postgres
  password: 12345678
  port: 5432
  pool: 5
  timeout: 5000
